/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppMarketRouteImport } from './routes/_app/market'
import { Route as AppNutriGrowRouteImport } from './routes/_app/nutri-grow'
import { Route as AppSuryaShaktiRouteImport } from './routes/_app/surya-shakti'
import { Route as AppWeatherRouteImport } from './routes/_app/weather'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppNutriGrowRoute = AppNutriGrowRouteImport.update({
  id: '/nutri-grow',
  path: '/nutri-grow',
  getParentRoute: () => AppRoute,
} as any)
const AppSuryaShaktiRoute = AppSuryaShaktiRouteImport.update({
  id: '/surya-shakti',
  path: '/surya-shakti',
  getParentRoute: () => AppRoute,
} as any)
const AppWeatherRoute = AppWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/market': typeof AppMarketRoute
  '/nutri-grow': typeof AppNutriGrowRoute
  '/surya-shakti': typeof AppSuryaShaktiRoute
  '/weather': typeof AppWeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/market': typeof AppMarketRoute
  '/nutri-grow': typeof AppNutriGrowRoute
  '/surya-shakti': typeof AppSuryaShaktiRoute
  '/weather': typeof AppWeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/market': typeof AppMarketRoute
  '/_app/nutri-grow': typeof AppNutriGrowRoute
  '/_app/surya-shakti': typeof AppSuryaShaktiRoute
  '/_app/weather': typeof AppWeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/market'
    | '/nutri-grow'
    | '/surya-shakti'
    | '/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/market'
    | '/nutri-grow'
    | '/surya-shakti'
    | '/weather'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/market'
    | '/_app/nutri-grow'
    | '/_app/surya-shakti'
    | '/_app/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/market': {
      id: '/_app/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nutri-grow': {
      id: '/_app/nutri-grow'
      path: '/nutri-grow'
      fullPath: '/nutri-grow'
      preLoaderRoute: typeof AppNutriGrowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surya-shakti': {
      id: '/_app/surya-shakti'
      path: '/surya-shakti'
      fullPath: '/surya-shakti'
      preLoaderRoute: typeof AppSuryaShaktiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/weather': {
      id: '/_app/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof AppWeatherRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppMarketRoute: typeof AppMarketRoute
  AppNutriGrowRoute: typeof AppNutriGrowRoute
  AppSuryaShaktiRoute: typeof AppSuryaShaktiRoute
  AppWeatherRoute: typeof AppWeatherRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppMarketRoute: AppMarketRoute,
  AppNutriGrowRoute: AppNutriGrowRoute,
  AppSuryaShaktiRoute: AppSuryaShaktiRoute,
  AppWeatherRoute: AppWeatherRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
